language: cpp
dist: xenial
sudo: required
compiler: gcc

# From https://gist.github.com/jreese/6207161#gistcomment-1462109
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

# From http://stackoverflow.com/q/37201085/3364162
#apt:
#  sources:
#    - ubuntu-sdk-team
#  packages:
#    - libqt5webkit5-dev
#    - qtdeclarative5-dev

# Xenial
services:
  - xvfb

# Trusty
# Start virtual X server
# before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

script: 
  - ./build.sh
  - ./travis_qmake_gcc_cpp98_qt5